ignoreWorkspaceRootCheck: true
shellEmulator: true
strictPeerDependencies: false

trustPolicy: no-downgrade
trustPolicyExclude:
  - vite@6.4.1
  - chokidar@4.0.3
  - semver@6.3.1

packages:
  - playground
  - examples/*

allowBuilds:
  esbuild: false
  sharp: false
  svelte-preprocess: false
  vue-demi: false
