/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const $$: typeof import('vue/macros')['$$']
  const $: typeof import('vue/macros')['$']
  const AAA: typeof import('xxx/es')['AAA']
  const BBB: typeof import('xxx/es')['BBB']
  const customFile: typeof import('../src/openapi/system/user/{id}/index')['customFile']
  const customFile1: typeof import('../src/openapi/system/user/{ id   }/index')['customFile']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, ComponentPublicInstance, ComputedRef, InjectionKey, PropType, Ref, VNode } from 'vue'
}
