import { ImportsMap } from '../types'

export default <ImportsMap>({
  '@headlessui/vue': [
    'Menu',
    'MenuButton',
    'MenuItems',
    'MenuItem',
    'Listbox',
    'ListboxButton',
    'ListboxOptions',
    'ListboxOption',
    'Switch',
    'SwitchGroup',
    'SwitchLabel',
    'SwitchDescription',
    'Disclosure',
    'DisclosureButton',
    'DisclosurePanel',
    'Dialog',
    'DialogOverlay',
    'DialogTitle',
    'DialogDescription',
    'Popover',
    'PopoverButton',
    'PopoverPanel',
    'PopoverOverlay',
    'PopoverGroup',
    'RadioGroup',
    'RadioGroupLabel',
    'RadioGroupOption',
    'RadioGroupDescription',
    'TransitionRoot',
    'TransitionChild',
    'TabGroup',
    'TabList',
    'Tab',
    'TabPanels',
    'TabPanel'
  ],
})
