import type { ImportsMap } from '../types'

export default <ImportsMap>({
  '@solidjs/router': [
    'A',
    'HashRouter',
    'MemoryRouter',
    'Navigate',
    'Route',
    'Router',
    'action',
    'createAsync',
    'createAsyncStore',
    'query',
    'revalidate',
    'useAction',
    'useSubmission',
    'useSubmissions',
    'useBeforeLeave',
    'useCurrentMatches',
    'useIsRouting',
    'useLocation',
    'useMatch',
    'useNavigate',
    'useParams',
    'usePreloadRoute',
    'useSearchParams',
    'json',
    'redirect',
    'reload',
  ],
})
